# Copyright (c) CloudBees, Inc.

#https://artifacthub.io/packages/helm/cloudbees/cloudbees-core/
#https://docs.cloudbees.com/docs/cloudbees-ci/latest/eks-install-guide/installing-eks-using-helm
#https://docs.cloudbees.com/docs/cloudbees-ci-kb/latest/best-practices/prepare-jenkins-for-support

Subdomain: true
OperationsCenter:
  JavaOpts: >-
      -Duser.timezone=Etc/UTC
      -XX:InitialRAMPercentage=50.0
      -XX:MaxRAMPercentage=50.0
      -XX:+AlwaysPreTouch
      -XX:+UseStringDeduplication
      -XX:+ParallelRefProcEnabled
      -XX:+HeapDumpOnOutOfMemoryError
      -XX:HeapDumpPath=/var/jenkins_home/logs
      -XX:+UnlockDiagnosticVMOptions
      -XX:+UnlockExperimentalVMOptions
      -Xlog:gc*=info,gc+heap=debug,gc+ref*=debug,gc+ergo*=trace,gc+age*=trace:file=/var/jenkins_home/gc.log:utctime,pid,level,tags:filecount=2,filesize=100M
      -XX:ErrorFile=/var/jenkins_home/logs/hs_err_%p.log
      -XX:+LogVMOutput
      -XX:LogFile=/var/jenkins_home/logs/jvm.log
  Resources:
    Limits:
      Memory: "4G"
      Cpu: 2
    Requests:
      Memory: "4G"
      Cpu: 2
  HostName: ${hosted_zone}
  Protocol: https
  Platform: eks
  Ingress:
    Class: alb
    Annotations:
      alb.ingress.kubernetes.io/scheme: internet-facing
      alb.ingress.kubernetes.io/certificate-arn: ${cert_arn}
  License:
    Evaluation:
      Enabled: true
      FirstName: ${LicFirstName}
      LastName: ${LicLastName}
      Email: ${LicEmail}
      Company: ${LicCompany}
Master:
  JavaOpts: >-
    -Duser.timezone=Etc/UTC
    -XX:InitialRAMPercentage=50.0
    -XX:MaxRAMPercentage=50.0
    -XX:+HeapDumpOnOutOfMemoryError
    -XX:HeapDumpPath=/var/jenkins_home/logs
    -XX:+UnlockDiagnosticVMOptions
    -XX:+UnlockExperimentalVMOptions
    -Xlog:gc*=info,gc+heap=debug,gc+ref*=debug,gc+ergo*=trace,gc+age*=trace:file=/var/jenkins_home/gc.log:utctime,pid,level,tags:filecount=2,filesize=100M
    -XX:ErrorFile=/var/jenkins_home/logs/hs_err_%p.log
    -XX:+LogVMOutput
    -XX:LogFile=/var/jenkins_home/logs/jvm.log
