# Copyright (c) CloudBees, Inc.

# https://artifacthub.io/packages/helm/cloudbees/cloudbees-core/
# https://docs.cloudbees.com/docs/cloudbees-ci/latest/eks-install-guide/installing-eks-using-helm

OperationsCenter:
  NodeSelector:
    role: ${cbciAppsNodeRole}
  Tolerations:
    - key: ${cbciAppsTolerationKey}
      operator: Equal
      value: ${cbciAppsTolerationValue}
      effect: NoSchedule
  CasC:
    Enabled: true
    Retriever:
      Enabled: true
      scmRepo: "https://github.com/cloudbees/terraform-aws-cloudbees-ci-eks-addon.git"
      scmBranch: main
      scmBundlePath: blueprints/02-at-scale/cbci/casc/oc
      scmPollingInterval: PT20M
Persistence:
  StorageClass: efs
Hibernation:
  Enabled: true
  NodeSelector:
    role: ${cbciAppsNodeRole}
  Tolerations:
    - key: ${cbciAppsTolerationKey}
      operator: Equal
      value: ${cbciAppsTolerationValue}
      effect: NoSchedule
Agents:
  SeparateNamespace:
    Enabled: true
    Create: true
    Name: ${cbciAgentsNamespace}
