# Copyright (c) CloudBees, Inc.

# IMPORTANT: Secrets must be parametrized or encrypted if they are saved in SCM.

sec_globalPassword: ${global_password}
sec_adminMail : ${adminMail}
sec_s3bucketName: ${s3bucketName}
sec_awsRegion: ${awsRegion}
sec_grafana_url: ${grafana_url}
