# Copyright (c) CloudBees, Inc.

# https://artifacthub.io/packages/helm/vmware-tanzu/velero
# https://github.com/vmware-tanzu/helm-charts/blob/main/charts/velero/values.yaml

nodeSelector:
  kubernetes.io/os: linux

kubectl:
  image:
    #Issue #60
    tag: 1.26.14-debian-11-r6
